import streamlit as st
import joblib
import numpy as np
import pytesseract
import re
from PIL import Image
from rdkit import Chem
from rdkit.Chem import AllChem
from thefuzz import process, fuzz
import pandas as pd
import pubchempy as pcp
import gspread
import csv
import os
from datetime import datetime

# ==========================================
# PAGE CONFIGURATION & STYLING
# ==========================================
st.set_page_config(page_title="NoxAI", page_icon="🔬", layout="wide")

# Custom CSS for background pattern and style the sidebar/uploader
custom_style = """
<style>
.stApp {
    background-image: url("data:image/svg+xml,%3Csvg width='100' height='100' viewBox='0 0 100 100' xmlns='http://www.w3.org/2000/svg'%3E%3Cg fill='none' stroke='%23888888' stroke-width='0.5' stroke-opacity='0.2'%3E%3Cpath d='M20 40l10-5 10 5v10l-10 5-10-5zM30 35v-10l8-4M40 40l8-2 4 6-6 4z'/%3E%3Cpath d='M70 70l8-4 8 4v8l-8 4-8-4zM86 70l5-8M70 78l-5 8'/%3E%3Ccircle cx='38' cy='21' r='1.5'/%3E%3Ccircle cx='48' cy='38' r='1.5'/%3E%3Ccircle cx='91' cy='62' r='1.5'/%3E%3C/g%3E%3C/svg%3E") !important;
    background-attachment: fixed !important;
}

[data-testid="stSidebar"] {
    background-color: rgba(128, 128, 128, 0.05) !important;
    backdrop-filter: blur(15px) !important;
    border-right: 1px solid rgba(128, 128, 128, 0.1) !important;
}

[data-testid="stFileUploader"] {
    background-color: rgba(128, 128, 128, 0.05) !important;
    border: 2px dashed rgba(128, 128, 128, 0.4) !important;
    border-radius: 12px !important;
    padding: 24px !important;
    transition: all 0.3s ease;
}

[data-testid="stFileUploader"]:hover {
    border-color: #3b82f6 !important;
    background-color: rgba(59, 130, 246, 0.05) !important;
}

[data-testid="stFileUploader"] section button {
    background-color: #3b82f6 !important; 
    color: #ffffff !important;
    border: none !important;
    border-radius: 6px !important;
    font-weight: 600 !important;
    padding: 0.5rem 1rem !important;
    transition: background-color 0.2s ease;
}

[data-testid="stFileUploader"] section button:hover {
    background-color: #2563eb !important;
}

div[data-baseweb="progress-bar"] > div {
    background-color: #3b82f6 !important; 
}

[data-testid="stFormSubmitButton"] button {
    background-color: #10b981 !important; 
    color: white !important;
    border: none !important;
    font-weight: bold !important;
    border-radius: 6px !important;
    transition: background-color 0.2s ease;
}

[data-testid="stFormSubmitButton"] button:hover {
    background-color: #059669 !important;
}
</style>
"""
st.markdown(custom_style, unsafe_allow_html=True)

# ==========================================
# INITIALIZATION & DATA LOADING
# ==========================================

# Configure Tesseract path (Required for local Windows machines)
pytesseract.pytesseract.tesseract_cmd = r'C:\Program Files\Tesseract-OCR\tesseract.exe'

# Load the trained machine learning model once at startup
model = joblib.load("toxicity_model.pkl")

@st.cache_data
def load_reference():
    """
    Loads and cleans the local chemical reference database.
    Cached by Streamlit to prevent reloading on every user interaction.
    """
    df = pd.read_csv("COSING.csv", on_bad_lines='skip')
    df['clean_name'] = df['INCI name'].astype(str).str.upper().str.replace(r'[^A-Z0-9]', '', regex=True)
    return df

df_reference = load_reference()
common_chems = df_reference['clean_name'].tolist()

# ==========================================
# CORE PROCESSING FUNCTIONS
# ==========================================
def process_image(img):
    """
    Extracts text from an uploaded image using Tesseract OCR,
    cleans the formatting, and splits it into a list of individual ingredients.
    """
    raw_text = pytesseract.image_to_string(img).upper()

    # Isolate the actual ingredient list by discarding marketing text before the headers
    for header in ["INGREDIENTS", "ACTIVE"]:
        if header in raw_text:
            raw_text = raw_text.split(header)[-1]

    if ":" in raw_text:
        text = raw_text.split(":")[-1]
    else:
        text = raw_text

    # Clean formatting and remove non-standard characters generated by OCR artifacts
    text = text.replace('\n', ' ').replace('\r', ' ')
    text = re.sub(r'[^A-Z0-9, ]', '', text)

    elem_list = []
    for i in text.split(','):
        molec = i.strip()

        # Filter out random single-letter OCR errors
        if len(molec) > 2:
            elem_list.append(molec)
    return elem_list

def predict(name):
    """
    Attempts to match an extracted ingredient name against the local database using fuzzy logic.
    If a match is found, passes it to the analysis engine.
    """
    clear_name = re.sub(r'[^A-Z0-9]', '', name.upper())

    # Use fuzzy matching to handle slight spelling errors or OCR misreads (Score out of 100)
    try_match = process.extractOne(clear_name, common_chems, scorer=fuzz.token_set_ratio)

    # Threshold set to 70 to ensure high confidence before assuming a match
    if try_match and try_match[1] > 70:
        return analyze(try_match[0])

    # Check if a substantial part of the chemical name exists within the string
    for chem in common_chems:
        if len(chem) > 5 and chem in clear_name:
            return analyze(chem)
    return "No Structure Found", "blue", name


def analyze(best_match):
    """
    Queries PubChem for chemical structures, generates a molecular fingerprint,
    and predicts toxicity using the trained Random Forest model.
    """

    # Fetch data from PubChem API
    results = pcp.get_compounds(best_match, 'name')

    if not results:
        return "Might not be in the database", "orange", best_match

    # Convert the SMILES string into a 2D molecule object using RDKit
    smiles = results[0].canonical_smiles
    mol = Chem.MolFromSmiles(smiles)
    if mol is None:
        return "Invalid Chemical", "gray", best_match

    # Generate a Morgan Fingerprint (numerical representation of molecular structure)
    generate = AllChem.GetMorganGenerator(radius=2, fpSize=2048)
    fp = generate.GetFingerprint(mol)

    # Pass the fingerprint to the ML model for safety prediction (1 = Toxic, 0 = Safe)
    prediction = model.predict([np.array(fp)])[0]
    if prediction == 1:
        status, color = "Not Safe!", "red"
    else:
        status, color = "Safe :)", "green"
    return status, color, best_match


def log_missing_chemical(original_name, attempted_name="."):
    """
    Logs unmatched chemicals to a Google Sheet (Cloud) or local CSV (Fallback).
    This helps the database administrator track emerging ingredients.
    """
    status = "Confirmed missing" if attempted_name == "." else "Correction failed"
    timestamp = datetime.now().strftime("%Y-%m-%d %H:%M:%S")

    try:
        # Securely authenticate using Streamlit Cloud Secrets
        credentials_dict = dict(st.secrets["gcp_service_account"])
        gc = gspread.service_account_from_dict(credentials_dict)

        # Target the specific Google Sheet document
        sheet = gc.open("NoxAI Logs").sheet1
        sheet.append_row([timestamp, original_name, attempted_name, status])

    except Exception as e:
        # Fallback to local CSV if running locally without secrets or if API fails
        st.warning(f"Could not connect to Google Sheets. Saving locally.")
        file_exists = os.path.isfile("admin_log.csv")
        with open("admin_log.csv", mode='a', newline='', encoding='utf-8') as f:
            writer = csv.writer(f)
            if not file_exists:
                writer.writerow(["Timestamp", "Original Name", "Attempted Correction", "Status"])
            writer.writerow([timestamp, original_name, attempted_name, status])

# ==========================================
# USER INTERFACE & LOGIC FLOW
# ==========================================
with st.sidebar:
    st.image("logo.png", width=150)
    st.title("NoxAI")
    st.write("Safety evaluation for complex ingredient lists.")
    st.info("Upload a clear photo of an ingredient list. Nox will cross-reference the European CosIng database.")

st.title("Ingredient Toxicity Scanner")
col1, col2 = st.columns([1, 1], gap="large")

with col1:
    st.subheader("1. Upload Label")
    file = st.file_uploader("Select an image...", type=['jpg', 'png', 'jpeg'])
    if file:
        img = Image.open(file)
        st.image(img, use_container_width=True)

with col2:
    st.subheader("2. NoxAI Analysis")
    if file:
        # Initialize session state to manage the manual review process without losing data
        if 'current_file' not in st.session_state or st.session_state.current_file != file.name:
            st.session_state.current_file = file.name
            st.session_state.scan_complete = False
            st.session_state.results = {}
            st.session_state.missing = []

        # 1. Automated Initial Scan
        if not st.session_state.scan_complete:
            with st.spinner("Nox is examining the label..."):
                ingredients = process_image(img)
                for item in ingredients:
                    status, color, match = predict(item)
                    if status in ["Might not be in the database", "No Structure Found"]:
                        st.session_state.missing.append(item)
                    else:
                        st.session_state.results[item] = (status, color, match)

                st.session_state.scan_complete = True
                st.rerun() # Refresh to show automated results

        # 2. Display Successfully Analyzed Ingredients
        for item, (status, color, match) in st.session_state.results.items():
            if status == "Safe :)":
                st.success(f"**{match}**: {status}")
            elif status == "Not Safe!":
                st.error(f"**{match}**: {status}")
            else:
                st.warning(f"**{match}**: Not in Database (logged to admin file)")

        # 3. Manual Review Form for Unrecognized Ingredients
        if st.session_state.missing:
            st.divider()
            st.subheader("Missing Ingredients")
            st.write(
                "The following items were not found. Correct the spelling, or enter '.' if the spelling is correct.")

            with st.form("manual_review_form"):
                corrections = {}
                for item in st.session_state.missing:
                    # Pre-fill with '.' so users only interact if a spelling correction is needed
                    corrections[item] = st.text_input(f"Review: **{item}**", value=".")

                submitted = st.form_submit_button("Submit Corrections & Finish Scan")

                if submitted:
                    with st.spinner("Processing corrections..."):
                        for item, correction in corrections.items():
                            clean_correction = correction.strip()

                            # User confirmed spelling is accurate; log to DB and flag locally
                            if clean_correction == ".":
                                log_missing_chemical(item, clean_correction)
                                st.session_state.results[item] = ("Not in database", "orange", item)

                            # User provided a correction; attempt to analyze new string
                            else:
                                new_s, new_c, new_m = analyze(clean_correction)

                                if new_s in ["Safe :)", "Not Safe!"]:
                                    st.session_state.results[item] = (new_s, new_c, new_m)

                                # Correction also failed; log to DB
                                else:
                                    log_missing_chemical(item, clean_correction)
                                    st.session_state.results[item] = ("Not in database", "orange", clean_correction)

                        # Clear missing queue to proceed to final verdict
                        st.session_state.missing = []
                        st.rerun()

        # 4. Final Product Verdict (only when no missing items remain)
        if st.session_state.scan_complete and not st.session_state.missing:
            st.divider()
            all_statuses = [res[0] for res in st.session_state.results.values()]
            # Use strict prioritization: a single unsafe item flags the whole product
            if "Not Safe!" in all_statuses:
                st.error("⚠️ **FINAL VERDICT: PRODUCT NOT SAFE**")
            elif "Safe :)" in all_statuses:
                st.success("✅ **FINAL VERDICT: PRODUCT LOOKS SAFE**")
            else:
                st.info(" ? **FINAL VERDICT: INCONCLUSIVE (items missing, we are solving the problem)**")
